name: example
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2
  intl_utils: ^2.8.10

dev_dependencies:
  custom_lint: ^0.7.5

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

  flutter_localization_linter:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - lib/l10n/

flutter_intl:
  enabled: true
